services:
  - type: web
    name: sysm
    runtime: node
    buildCommand: cd client && npm install && node node_modules/vite/bin/vite.js build && cd ../server && npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
